### ISSUE TITLE
I could not find any songs that can be played right now

### ISSUE THREAD

**Issue by bliekp** [athombv/com.spotify#4] opened 2017-08-31 05:26 UTC
All the songs n Spotify are greyed out and when clicking on Play Homey tells me: I could not find any songs that can be played right now 
So far no luck... 
Also connecting to my Onkyo receiver which supports Spotify Connect does not work. 
At this moment this app does nothing for me...
On latest Homey beta software. I have Spotify Premium.

**Comment by mauritsivs** [comment] 2017-09-19 11:20
same here,
all my playlists appear, but all songs are grayed out

**Comment by DieterKoblenz** [comment] 2017-09-25 07:37
Same here unfortunately. And timed out when searching for songs.

**Comment by cjvs** [comment] 2017-09-26 11:52
Same here, has never worked for me yet... (only have homey out and a chromecast)

**Comment by laurkaarna** [comment] 2017-10-01 09:41
Same here also. 
Spotify 1.1.2 beta and Homey 1.5.3

I'm using chromecast audio. Got it working for a second when i changed the volume (at least the playlist wasnt greyed out anymore) but i'm unable to reproduce this.

Works if i choose my mac as the speaker where spotify is running.

**Comment by BasKiers** [comment] 2017-10-30 12:27
Hi, 

This bug should be fixed as of Spotify v1.1.3

**Closed by BasKiers** 2017-10-30 12:27 UTC

**Comment by cjvs** [comment] 2017-10-31 12:57
@BasKiers , I removed the spotify app, reinstalled v 1.1.3, updated to 1.1.4 today, did a reboot... However still "I could not find any songs that can be played right now". It takes very long for homey to start the app...

Is there anything I may need to do to completely remove the app and reinstall?
